### ISSUE TITLE
Remove rails dependency

### ISSUE THREAD

**Issue by mneumark** [wireframe/backgrounded#13]
I use an app that is Sinatra based but uses ActiveRecord. I'd like to add this in, but I don't want the overhead of needing all of rails. That and the fact that Sinatra 1.4.7, currently the latest, forces Rack at 1.5. I am using Active Record 5, so its using Rails 5, which needs actionpack 5, which needs rack 2.0, which Sinatra does not support.

If you only required ActiveRecord and Active Support, it would be just as functional, but more compatible, and you'd be requiring less, which is good.

**Comment by mneumark** [comment]
Actually [wrote a PR](https://github.com/wireframe/backgrounded/pull/14) for you.

**Comment by wireframe** [comment]
closed by #14
